[phases.setup]
nixPkgs = ["python313", "libpq"]

[phases.install]
cmds = ["python -m venv /app/.venv", "pip install -r requirements.txt"]

[start]
cmd = "uvicorn server:app --host 0.0.0.0 --port ${PORT:-8000}"
